# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-25 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='苏州吴中区', max_length=64),
        ),
    ]
