# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181029_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='app01.Book'),
        ),
    ]
